version: 0.2
run-as: yoctouser

env:
  shell: bash
  # HOME is set to /root even when running as a non-root user.
  variables:
    HOME: "/home/yoctouser"

phases:
  pre_build:
    run-as: root
    commands:
      - chown -R yoctouser /sstate-cache
      - chown -R yoctouser /downloads
      - chmod 755 /sstate-cache
      - chmod 755 /downloads
  build:
    commands:
      - echo Build started on `date`
      - repo init -u https://github.com/nxp-imx/imx-manifest -b imx-linux-mickledore -m imx-6.1.22-2.0.0.xml
      - repo sync
      - MACHINE=imx6ullevk DISTRO=poky . setup-environment $TMP_DIR
      # Update our local conf to check for CVEs
      - echo 'INHERIT += "cve-check"' >> $TMP_DIR/conf/local.conf
      # this will suppress false positive CVEs
      - echo 'include cve-extra-exclusions.inc' >> $TMP_DIR/conf/local.conf
      # build the image
      - bitbake core-image-minimal
  post_build:
    commands:
      # Prune old files in our EFS Mounts, that are not accessed by this or any build within 30 days
      - find /sstate-cache -atime +30 -delete
      - find /downloads -atime +30 -delete

artifacts:
  discard-paths: true
  files:
    - $TMP_DIR/tmp/deploy/images/qemux86-64/core-image-minimal-qemux86-64*
    - $TMP_DIR/tmp/log/cve/cve-summary*
